// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxvIs7YiT3DIr9qJjV6GC4wrRuRvwurs',
    appId: '1:1069072609963:web:eaae077db66a0a251bfdee',
    messagingSenderId: '1069072609963',
    projectId: 'ecommerce-app-3fefd',
    authDomain: 'ecommerce-app-3fefd.firebaseapp.com',
    storageBucket: 'ecommerce-app-3fefd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDj0G4XTULwWDrW5_GLfFieCeZCHNjoY',
    appId: '1:1069072609963:android:b6f23d37be07e8171bfdee',
    messagingSenderId: '1069072609963',
    projectId: 'ecommerce-app-3fefd',
    storageBucket: 'ecommerce-app-3fefd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7eKPlBdBW80x5G1rLGg_G-xEpelccy0Q',
    appId: '1:1069072609963:ios:bcf0bdf9e2ff3e131bfdee',
    messagingSenderId: '1069072609963',
    projectId: 'ecommerce-app-3fefd',
    storageBucket: 'ecommerce-app-3fefd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7eKPlBdBW80x5G1rLGg_G-xEpelccy0Q',
    appId: '1:1069072609963:ios:bcf0bdf9e2ff3e131bfdee',
    messagingSenderId: '1069072609963',
    projectId: 'ecommerce-app-3fefd',
    storageBucket: 'ecommerce-app-3fefd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXxvIs7YiT3DIr9qJjV6GC4wrRuRvwurs',
    appId: '1:1069072609963:web:adae86039738cea71bfdee',
    messagingSenderId: '1069072609963',
    projectId: 'ecommerce-app-3fefd',
    authDomain: 'ecommerce-app-3fefd.firebaseapp.com',
    storageBucket: 'ecommerce-app-3fefd.firebasestorage.app',
  );
}
